// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "c4Thp8KUfnKwuumytH0Wp57BJu5nn82wn4NVdErxXGgm3EPEzqgQ2g0YJ4lzyu9cx2KBe4";
}
}
}

